name: Update README with Latest Repositories

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch: 
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://github.com/franocella.atom"
          max_post_count: 3
          template: "- **[$title]($url)**: *$description...*"
          readme_path: "README.md"
          comment_tag_name: "LATEST-REPOS"
